name: Laptop88

on:
  schedule:
    - cron: "0 0 * * 0"   # chạy mỗi Chủ Nhật
  workflow_dispatch:

jobs:
  laptop88:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3
      with:
        token: ${{ secrets.GITHUB_TOKEN }}

    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.10"

    - name: Install dependencies
      run: |
        pip install requests
        pip install beautifulsoup4

    - name: Run Laptop88 crawler
      run: python laptop88.py

    - name: Commit results
      run: |
        git config --global user.name "github-actions"
        git config --global user.email "github-actions@github.com"
        git add output/laptop88.csv
        git commit -m "Update Laptop88" || echo "No changes"
        git push https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git
