name: LaptopWorld

on:
  schedule:
    - cron: "0 0 * * 0"   # chạy mỗi Chủ Nhật
  workflow_dispatch:

jobs:
  crawl:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3
      with:
        token: ${{ secrets.GITHUB_TOKEN }}

    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.10"

    - name: Install dependencies
      run: |
        pip install selenium
        pip install webdriver-manager
        pip install beautifulsoup4
        pip install pandas

    - name: Install Chrome
      run: |
        sudo apt-get update
        sudo apt-get install -y google-chrome-stable

    - name: Run LaptopWorld crawler
      run: python Laptopworld.py

    - name: Commit results
      run: |
        git config --global user.name "github-actions"
        git config --global user.email "github-actions@github.com"
        git add output/laptopworld.csv
        git commit -m "LaptopWorld update" || echo "No changes"
        git push https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git
